examples: add a basic crane example
nikstur/bombon pull request #106
Opened 2024-06-24 15:55 UTC by 0xf09f95b4

This PR adds a basic example for rust builds using crane.

It shows how to extend the existing simple crane example with `bombon.lib.${system}.passthruVendoredSbom.rust` to generate SBOMs for a crane binary.

2024-07-02 11:43 UTC, nikstur requested changes
If you remove the deny.toml, this is good to go.

2024-07-02 11:43 UTC, nikstur commented on examples/crane/deny.toml
We don't really need this here.

2024-07-04 12:44 UTC, 0xf09f95b4 commented on examples/crane/deny.toml
I wanted to stay close to the minimal `crane` example but you're right -- it's needless overhead.

Done!

2024-07-12 13:40 UTC, nikstur approved these changes

2024-07-12 13:40 UTC, merged